### ISSUE TITLE
提案:二番目のREADME.mdをマージまたは移動する

### ISSUE THREAD

**Issue by fu7mu4** [histudy/infra#4]
一つのOSSにREADME.mdファイルが複数ありますがあまり見ない構成です。OSSの内部に別のOSSが含まれている場合にはありますが、このプロジェクトはそうではないと思います。

対応としてはどれがいいでしょうか?

1  プロジェクト直下のREADME.mdにマージする
2  プロジェクト直下に移動し別の名前にする
3  プロジェクト直下にdocフォルダを作成してそちらに移動し、プロジェクト直下のREADME.mdにdoc以下を参照するように追記する。
4  そのまま

**Comment by 223n** [comment]
@fu7mu4 今回のマージで修正を行いましたが、どうでしょうか？

**Comment by fu7mu4** [comment]
この修正でよいと思います。本件をクローズします。
